Testing

diff --git a/.github/workflows/appsignals-e2e-test.yml b/.github/workflows/appsignals-e2e-test.yml
--- a/.github/workflows/appsignals-e2e-test.yml
+++ b/.github/workflows/appsignals-e2e-test.yml
@@ -124,180 +124,180 @@ jobs:
           echo "OLD_CW_AGENT_OPERATOR_IMAGE"=$(kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=amazon-cloudwatch-observability -o json | \
           jq '.items[0].status.containerStatuses[0].image') >> $GITHUB_ENV
 
-      - name: Patch the CloudWatch Agent Operator image and restart CloudWatch pods
-        run: |
-          kubectl patch deploy -n amazon-cloudwatch amazon-cloudwatch-observability-controller-manager --type='json' -p '[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "${{ env.ECR_OPERATOR_STAGING_IMAGE }}"}]'
-          kubectl delete pods --all -n amazon-cloudwatch
-          kubectl wait --for=condition=Ready pod --all -n amazon-cloudwatch
-
-      # Application pods need to be restarted for the
-      # app signals instrumentation to take effect
-      - name: Restart the app pods
-        run: kubectl delete pods --all -n ${{ env.SAMPLE_APP_NAMESPACE }}
-
-      - name: Wait for sample app pods to come up
-        run: |
-          kubectl wait --for=condition=Ready pod --all -n ${{ env.SAMPLE_APP_NAMESPACE }} \
-
-      - name: Get remote service deployment name and IP
-        run: |
-          echo "REMOTE_SERVICE_DEPLOYMENT_NAME=$(kubectl get deployments -n ${{ env.SAMPLE_APP_NAMESPACE }} --selector=app=remote-app -o jsonpath='{.items[0].metadata.name}')" >> $GITHUB_ENV
-          echo "REMOTE_SERVICE_POD_IP=$(kubectl get pods -n ${{ env.SAMPLE_APP_NAMESPACE }} --selector=app=remote-app -o jsonpath='{.items[0].status.podIP}')" >> $GITHUB_ENV
-
-      - name: Log pod ADOT image ID
-        run: |
-          kubectl get pods -n ${{ env.SAMPLE_APP_NAMESPACE }} --output json | \
-          jq '.items[0].status.initContainerStatuses[0].imageID'
-
-      - name: Log pod CWAgent image ID
-        run: |
-          kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=cloudwatch-agent -o json | \
-          jq '.items[0].status.containerStatuses[0].imageID'
-
-      - name: Log pod CWAgent Operator image ID and save image to the environment
-        run: |
-          kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=amazon-cloudwatch-observability -o json | \
-          jq '.items[0].status.containerStatuses[0].imageID'
-          
-          echo "NEW_CW_AGENT_OPERATOR_IMAGE"=$(kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=amazon-cloudwatch-observability -o json | \
-          jq '.items[0].status.containerStatuses[0].image') >> $GITHUB_ENV
-
-      - name: Check if CW Agent Operator image has changed
-        run: |
-          if [ ${{ env.OLD_CW_AGENT_OPERATOR_IMAGE }} = ${{ env.NEW_CW_AGENT_OPERATOR_IMAGE }} ]; then
-            echo "Operator image did not change"
-            exit 1
-          fi
-
+#      - name: Patch the CloudWatch Agent Operator image and restart CloudWatch pods
+#        run: |
+#          kubectl patch deploy -n amazon-cloudwatch amazon-cloudwatch-observability-controller-manager --type='json' -p '[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "${{ env.ECR_OPERATOR_STAGING_IMAGE }}"}]'
+#          kubectl delete pods --all -n amazon-cloudwatch
+#          kubectl wait --for=condition=Ready pod --all -n amazon-cloudwatch
+#
+#      # Application pods need to be restarted for the
+#      # app signals instrumentation to take effect
+#      - name: Restart the app pods
+#        run: kubectl delete pods --all -n ${{ env.SAMPLE_APP_NAMESPACE }}
+#
+#      - name: Wait for sample app pods to come up
+#        run: |
+#          kubectl wait --for=condition=Ready pod --all -n ${{ env.SAMPLE_APP_NAMESPACE }} \
+#
+#      - name: Get remote service deployment name and IP
+#        run: |
+#          echo "REMOTE_SERVICE_DEPLOYMENT_NAME=$(kubectl get deployments -n ${{ env.SAMPLE_APP_NAMESPACE }} --selector=app=remote-app -o jsonpath='{.items[0].metadata.name}')" >> $GITHUB_ENV
+#          echo "REMOTE_SERVICE_POD_IP=$(kubectl get pods -n ${{ env.SAMPLE_APP_NAMESPACE }} --selector=app=remote-app -o jsonpath='{.items[0].status.podIP}')" >> $GITHUB_ENV
+#
+#      - name: Log pod ADOT image ID
+#        run: |
+#          kubectl get pods -n ${{ env.SAMPLE_APP_NAMESPACE }} --output json | \
+#          jq '.items[0].status.initContainerStatuses[0].imageID'
+#
+#      - name: Log pod CWAgent image ID
+#        run: |
+#          kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=cloudwatch-agent -o json | \
+#          jq '.items[0].status.containerStatuses[0].imageID'
+#
+#      - name: Log pod CWAgent Operator image ID and save image to the environment
+#        run: |
+#          kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=amazon-cloudwatch-observability -o json | \
+#          jq '.items[0].status.containerStatuses[0].imageID'
+#
+#          echo "NEW_CW_AGENT_OPERATOR_IMAGE"=$(kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/name=amazon-cloudwatch-observability -o json | \
+#          jq '.items[0].status.containerStatuses[0].image') >> $GITHUB_ENV
+#
+#      - name: Check if CW Agent Operator image has changed
+#        run: |
+#          if [ ${{ env.OLD_CW_AGENT_OPERATOR_IMAGE }} = ${{ env.NEW_CW_AGENT_OPERATOR_IMAGE }} ]; then
+#            echo "Operator image did not change"
+#            exit 1
+#          fi
+#
       - name: Get the sample app endpoint
         run: |
           echo "APP_ENDPOINT=$(terraform output sample_app_endpoint)" >> $GITHUB_ENV
         working-directory: testing/terraform/eks
-
-      - name: Wait for app endpoint to come online
-        id: endpoint-check
-        run: |
-          attempt_counter=0
-          max_attempts=30
-          until $(curl --output /dev/null --silent --head --fail http://${{ env.APP_ENDPOINT }}); do
-            if [ ${attempt_counter} -eq ${max_attempts} ];then
-              echo "Max attempts reached"
-              exit 1
-            fi
-
-            printf '.'
-            attempt_counter=$(($attempt_counter+1))
-            sleep 10
-          done
-
-      # This steps increases the speed of the validation by creating the telemetry data in advance
-      - name: Call all test APIs
-        continue-on-error: true
-        run: |
-          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/outgoing-http-call/
-          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/aws-sdk-call/
-          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/remote-service?ip=${{ env.REMOTE_SERVICE_POD_IP }}/
-          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/client-call/
-
-      # Validation for app signals telemetry data
-      - name: Call endpoint and validate generated EMF logs
-        id: log-validation
-        if: steps.endpoint-check.outcome == 'success' && !cancelled()
-        run: ./gradlew testing:validator:run --args='-c eks/log-validation.yml
-          --testing-id ${{ env.TESTING_ID }}
-          --endpoint http://${{ env.APP_ENDPOINT }}
-          --region ${{ env.AWS_DEFAULT_REGION }}
-          --account-id ${{ env.TEST_ACCOUNT }}
-          --metric-namespace ${{ env.METRIC_NAMESPACE }}
-          --log-group ${{ env.LOG_GROUP }}
-          --app-namespace ${{ env.SAMPLE_APP_NAMESPACE }}
-          --platform-info ${{ inputs.test-cluster-name }}
-          --service-name sample-application-${{ env.TESTING_ID }}
-          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_DEPLOYMENT_NAME }}
-          --request-body ip=${{ env.REMOTE_SERVICE_POD_IP }}
-          --rollup'
-
-      - name: Call endpoints and validate generated metrics
-        id: metric-validation
-        if: (success() || steps.log-validation.outcome == 'failure') && !cancelled()
-        run: ./gradlew testing:validator:run --args='-c eks/metric-validation.yml
-          --testing-id ${{ env.TESTING_ID }}
-          --endpoint http://${{ env.APP_ENDPOINT }}
-          --region ${{ env.AWS_DEFAULT_REGION }}
-          --account-id ${{ env.TEST_ACCOUNT }}
-          --metric-namespace ${{ env.METRIC_NAMESPACE }}
-          --log-group ${{ env.LOG_GROUP }}
-          --app-namespace ${{ env.SAMPLE_APP_NAMESPACE }}
-          --platform-info ${{ inputs.test-cluster-name }}
-          --service-name sample-application-${{ env.TESTING_ID }}
-          --remote-service-name sample-remote-application-${{ env.TESTING_ID }}
-          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_DEPLOYMENT_NAME }}
-          --request-body ip=${{ env.REMOTE_SERVICE_POD_IP }}
-          --rollup'
-
-      - name: Call endpoints and validate generated traces
-        id: trace-validation
-        if: (success() || steps.log-validation.outcome == 'failure' || steps.metric-validation.outcome == 'failure') && !cancelled()
-        run: ./gradlew testing:validator:run --args='-c eks/trace-validation.yml
-          --testing-id ${{ env.TESTING_ID }}
-          --endpoint http://${{ env.APP_ENDPOINT }}
-          --region ${{ env.AWS_DEFAULT_REGION }}
-          --account-id ${{ env.TEST_ACCOUNT }}
-          --metric-namespace ${{ env.METRIC_NAMESPACE }}
-          --log-group ${{ env.LOG_GROUP }}
-          --app-namespace ${{ env.SAMPLE_APP_NAMESPACE }}
-          --platform-info ${{ inputs.test-cluster-name }}
-          --service-name sample-application-${{ env.TESTING_ID }}
-          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_DEPLOYMENT_NAME }}
-          --request-body ip=${{ env.REMOTE_SERVICE_POD_IP }}
-          --rollup'
-
-      # Clean up Procedures
-
-      - name: Remove log group deletion command
-        if: always()
-        working-directory: enablement-script/scripts/eks/appsignals
-        run: |
-          delete_log_group="aws logs delete-log-group --log-group-name '${{ env.LOG_GROUP }}' --region \$REGION"
-          sed -i "s#$delete_log_group##g" clean-app-signals.sh
-
-      - name: Clean Up App Signals
-        if: always()
-        continue-on-error: true
-        working-directory: enablement-script/scripts/eks/appsignals
-        run: |
-          ./clean-app-signals.sh \
-          ${{ inputs.test-cluster-name }} \
-          ${{ env.AWS_DEFAULT_REGION }} \
-          ${{ env.SAMPLE_APP_NAMESPACE }}
-
-      # This step also deletes lingering resources from previous test runs
-      - name: Delete all sample app resources
-        if: always()
-        continue-on-error: true
-        timeout-minutes: 10
-        run: kubectl delete namespace ${{ env.SAMPLE_APP_NAMESPACE }}
-
-      - name: Terraform destroy
-        if: always()
-        continue-on-error: true
-        working-directory: testing/terraform/eks
-        run: |
-          terraform destroy -auto-approve \
-            -var="test_id=${{ env.TESTING_ID }}" \
-            -var="aws_region=${{ env.AWS_DEFAULT_REGION }}" \
-            -var="kube_directory_path=${{ github.workspace }}/.kube" \
-            -var="eks_cluster_name=${{ inputs.test-cluster-name }}" \
-            -var="test_namespace=${{ env.SAMPLE_APP_NAMESPACE }}" \
-            -var="service_account_aws_access=service-account-${{ env.TESTING_ID }}" \
-            -var="sample_app_image=${{ env.SAMPLE_APP_IMAGE }}"
-
-      - name: Remove aws access service account
-        if: always()
-        continue-on-error: true
-        run: |
-          eksctl delete iamserviceaccount \
-          --name service-account-${{ env.TESTING_ID }} \
-          --namespace ${{ env.SAMPLE_APP_NAMESPACE }} \
-          --cluster ${{ inputs.test-cluster-name }} \
-          --region ${{ env.AWS_DEFAULT_REGION }}
+#
+#      - name: Wait for app endpoint to come online
+#        id: endpoint-check
+#        run: |
+#          attempt_counter=0
+#          max_attempts=30
+#          until $(curl --output /dev/null --silent --head --fail http://${{ env.APP_ENDPOINT }}); do
+#            if [ ${attempt_counter} -eq ${max_attempts} ];then
+#              echo "Max attempts reached"
+#              exit 1
+#            fi
+#
+#            printf '.'
+#            attempt_counter=$(($attempt_counter+1))
+#            sleep 10
+#          done
+#
+#      # This steps increases the speed of the validation by creating the telemetry data in advance
+#      - name: Call all test APIs
+#        continue-on-error: true
+#        run: |
+#          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/outgoing-http-call/
+#          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/aws-sdk-call/
+#          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/remote-service?ip=${{ env.REMOTE_SERVICE_POD_IP }}/
+#          curl -S -s -o /dev/null http://${{ env.APP_ENDPOINT }}/client-call/
+#
+#      # Validation for app signals telemetry data
+#      - name: Call endpoint and validate generated EMF logs
+#        id: log-validation
+#        if: steps.endpoint-check.outcome == 'success' && !cancelled()
+#        run: ./gradlew testing:validator:run --args='-c eks/log-validation.yml
+#          --testing-id ${{ env.TESTING_ID }}
+#          --endpoint http://${{ env.APP_ENDPOINT }}
+#          --region ${{ env.AWS_DEFAULT_REGION }}
+#          --account-id ${{ env.TEST_ACCOUNT }}
+#          --metric-namespace ${{ env.METRIC_NAMESPACE }}
+#          --log-group ${{ env.LOG_GROUP }}
+#          --app-namespace ${{ env.SAMPLE_APP_NAMESPACE }}
+#          --platform-info ${{ inputs.test-cluster-name }}
+#          --service-name sample-application-${{ env.TESTING_ID }}
+#          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_DEPLOYMENT_NAME }}
+#          --request-body ip=${{ env.REMOTE_SERVICE_POD_IP }}
+#          --rollup'
+#
+#      - name: Call endpoints and validate generated metrics
+#        id: metric-validation
+#        if: (success() || steps.log-validation.outcome == 'failure') && !cancelled()
+#        run: ./gradlew testing:validator:run --args='-c eks/metric-validation.yml
+#          --testing-id ${{ env.TESTING_ID }}
+#          --endpoint http://${{ env.APP_ENDPOINT }}
+#          --region ${{ env.AWS_DEFAULT_REGION }}
+#          --account-id ${{ env.TEST_ACCOUNT }}
+#          --metric-namespace ${{ env.METRIC_NAMESPACE }}
+#          --log-group ${{ env.LOG_GROUP }}
+#          --app-namespace ${{ env.SAMPLE_APP_NAMESPACE }}
+#          --platform-info ${{ inputs.test-cluster-name }}
+#          --service-name sample-application-${{ env.TESTING_ID }}
+#          --remote-service-name sample-remote-application-${{ env.TESTING_ID }}
+#          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_DEPLOYMENT_NAME }}
+#          --request-body ip=${{ env.REMOTE_SERVICE_POD_IP }}
+#          --rollup'
+#
+#      - name: Call endpoints and validate generated traces
+#        id: trace-validation
+#        if: (success() || steps.log-validation.outcome == 'failure' || steps.metric-validation.outcome == 'failure') && !cancelled()
+#        run: ./gradlew testing:validator:run --args='-c eks/trace-validation.yml
+#          --testing-id ${{ env.TESTING_ID }}
+#          --endpoint http://${{ env.APP_ENDPOINT }}
+#          --region ${{ env.AWS_DEFAULT_REGION }}
+#          --account-id ${{ env.TEST_ACCOUNT }}
+#          --metric-namespace ${{ env.METRIC_NAMESPACE }}
+#          --log-group ${{ env.LOG_GROUP }}
+#          --app-namespace ${{ env.SAMPLE_APP_NAMESPACE }}
+#          --platform-info ${{ inputs.test-cluster-name }}
+#          --service-name sample-application-${{ env.TESTING_ID }}
+#          --remote-service-deployment-name ${{ env.REMOTE_SERVICE_DEPLOYMENT_NAME }}
+#          --request-body ip=${{ env.REMOTE_SERVICE_POD_IP }}
+#          --rollup'
+#
+#      # Clean up Procedures
+#
+#      - name: Remove log group deletion command
+#        if: always()
+#        working-directory: enablement-script/scripts/eks/appsignals
+#        run: |
+#          delete_log_group="aws logs delete-log-group --log-group-name '${{ env.LOG_GROUP }}' --region \$REGION"
+#          sed -i "s#$delete_log_group##g" clean-app-signals.sh
+#
+#      - name: Clean Up App Signals
+#        if: always()
+#        continue-on-error: true
+#        working-directory: enablement-script/scripts/eks/appsignals
+#        run: |
+#          ./clean-app-signals.sh \
+#          ${{ inputs.test-cluster-name }} \
+#          ${{ env.AWS_DEFAULT_REGION }} \
+#          ${{ env.SAMPLE_APP_NAMESPACE }}
+#
+#      # This step also deletes lingering resources from previous test runs
+#      - name: Delete all sample app resources
+#        if: always()
+#        continue-on-error: true
+#        timeout-minutes: 10
+#        run: kubectl delete namespace ${{ env.SAMPLE_APP_NAMESPACE }}
+#
+#      - name: Terraform destroy
+#        if: always()
+#        continue-on-error: true
+#        working-directory: testing/terraform/eks
+#        run: |
+#          terraform destroy -auto-approve \
+#            -var="test_id=${{ env.TESTING_ID }}" \
+#            -var="aws_region=${{ env.AWS_DEFAULT_REGION }}" \
+#            -var="kube_directory_path=${{ github.workspace }}/.kube" \
+#            -var="eks_cluster_name=${{ inputs.test-cluster-name }}" \
+#            -var="test_namespace=${{ env.SAMPLE_APP_NAMESPACE }}" \
+#            -var="service_account_aws_access=service-account-${{ env.TESTING_ID }}" \
+#            -var="sample_app_image=${{ env.SAMPLE_APP_IMAGE }}"
+#
+#      - name: Remove aws access service account
+#        if: always()
+#        continue-on-error: true
+#        run: |
+#          eksctl delete iamserviceaccount \
+#          --name service-account-${{ env.TESTING_ID }} \
+#          --namespace ${{ env.SAMPLE_APP_NAMESPACE }} \
+#          --cluster ${{ inputs.test-cluster-name }} \
+#          --region ${{ env.AWS_DEFAULT_REGION }}
