apm setup

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -5,13 +5,13 @@ env:
 on:
   push:
     branches:
-      - integ-test-eks-addon
+      - testing
     paths-ignore:
       - '**/*.md'
       - 'NOTICE'
       - 'LICENSE'
       - '.github/**'
-      - '!.github/workflows/integration-test.yml'
+#      - '!.github/workflows/integration-test.yml'
   workflow_dispatch:
 
 concurrency:
@@ -23,8 +23,8 @@ permissions:
   contents: read
 
 jobs:
-  EKSAddOnIntegrationTest:
-    name: EKSAddOnIntegrationTest
+  OperatorIntegrationTest:
+    name: OperatorIntegrationTest
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -40,10 +40,7 @@ jobs:
         uses: aws-actions/configure-aws-credentials@v2
         with:
           role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
-          aws-region: us-east-1
-
-      - name: Verify Terraform version
-        run: terraform --version
+          aws-region: us-west-2
 
       - name: Terraform apply
         uses: nick-fields/retry@v2
@@ -72,3 +69,55 @@ jobs:
             cd integration-tests/terraform/eks
 
             terraform destroy --auto-approve
+            
+            
+
+#  EKSAddOnIntegrationTest:
+#    name: EKSAddOnIntegrationTest
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#    permissions:
+#      id-token: write
+#      contents: read
+#    steps:
+#      - uses: actions/checkout@v3
+#        with:
+#          fetch-depth: 0
+#
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v2
+#        with:
+#          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
+#          aws-region: us-east-1
+#
+#      - name: Verify Terraform version
+#        run: terraform --version
+#
+#      - name: Terraform apply
+#        uses: nick-fields/retry@v2
+#        with:
+#          max_attempts: 1
+#          timeout_minutes: 60 # EKS takes about 20 minutes to spin up a cluster and service on the cluster
+#          retry_wait_seconds: 5
+#          command: |
+#            cd integration-tests/terraform/eks
+#
+#            terraform init
+#            if terraform apply --auto-approve; then
+#              terraform destroy -auto-approve
+#            else
+#              terraform destroy -auto-approve && exit 1
+#            fi
+#
+#      - name: Terraform destroy
+#        if: ${{ cancelled() || failure() }}
+#        uses: nick-fields/retry@v2
+#        with:
+#          max_attempts: 3
+#          timeout_minutes: 8
+#          retry_wait_seconds: 5
+#          command: |
+#            cd integration-tests/terraform/eks
+#
+#            terraform destroy --auto-approve
