edited yml

diff --git a/.github/workflows/OperatorIntegrtionTest.yml b/.github/workflows/OperatorIntegrtionTest.yml
--- a/.github/workflows/OperatorIntegrtionTest.yml
+++ b/.github/workflows/OperatorIntegrtionTest.yml
@@ -53,7 +53,28 @@ jobs:
           sleep 10
           kubectl get pods -A
           kubectl logs -l app.kubernetes.io/name=amazon-cloudwatch-agent-operator -n amazon-cloudwatch --tail=100
-
+      - name: Apply cloudwatch-agent.yaml
+        run: |
+          cd integration-tests/operator
+          kubectl apply -f amazoncloudwatchagent.yaml
+          sleep 10
+          kubectl apply -f ./sample-instrumentation.yaml
+          sleep 10
+          kubectl apply -f ./test-deployment.yaml
+          sleep 60
+          kubectl get all -n amazon-cloudwatch
+          kubectl get pods -A
+          kubectl describe deployment amazon-cloudwatch-observability-controller-manager -n amazon-cloudwatch
+          pod_name="$(kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/component=amazon-cloudwatch-agent,app.kubernetes.io/instance=amazon-cloudwatch.cloudwatch-agent -o=jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}')"
+          status=$(kubectl get pod "$pod_name" -n amazon-cloudwatch -o=jsonpath='{.status.phase}')
+          if [ "$status" != "Running" ]; then
+            echo "Pod $pod_name is not running. Exiting with ERROR."
+            echo "Testcase 1: Pod running test case: FAIL"
+            terraform destroy  -auto-approve && exit 1
+          else
+            echo "Pod $pod_name is running."
+            echo "Testcase 1: Pod running test case: PASS"
+          fi
       # Apply amazoncloudwatchagent.yaml
 
       # Verify cloudwatch-agent deployed in amazon-cloudwatch namespace as daemonset with 2 pods
