edited yml

diff --git a/.github/workflows/OperatorIntegrtionTest.yml b/.github/workflows/OperatorIntegrtionTest.yml
--- a/.github/workflows/OperatorIntegrtionTest.yml
+++ b/.github/workflows/OperatorIntegrtionTest.yml
@@ -145,6 +145,10 @@ jobs:
                 kubectl describe pod nginx -n amazon-cloudwatch
                 cd cmd
                 go run ./test_default_instrumentation_main.go
+                if [ $? -ne 0 ]; then
+                  echo "error in go lang file"
+                  terraform destroy  -auto-approve && exit 1
+                fi
               fi
             else
               terraform destroy  -auto-approve && exit 1
