edited yml

diff --git a/.github/workflows/OperatorIntegrtionTest.yml b/.github/workflows/OperatorIntegrtionTest.yml
--- a/.github/workflows/OperatorIntegrtionTest.yml
+++ b/.github/workflows/OperatorIntegrtionTest.yml
@@ -15,48 +15,22 @@ on:
   workflow_call:
 
 jobs:
-  MakeBinary:
-    name: 'MakeContainerImage'
+  IntegrationTest:
+    name: 'GenerateTestMatrix'
     runs-on: ubuntu-latest
-    permissions:
-      id-token: write
-      contents: read
     steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-
-      - name: Set up Go 1.x
-        uses: actions/setup-go@v4
-        with:
-          go-version: ~1.19.6
-          cache: false
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
-          aws-region: us-west-2
-
-      - name: Login to ECR
-        if: steps.cached_binaries.outputs.cache-hit == false
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
-
-      - name: Set up Docker Buildx
-        if: steps.cached_binaries.outputs.cache-hit == false
-        uses: docker/setup-buildx-action@v1
-
-      - name: Set up QEMU
-        if: steps.cached_binaries.outputs.cache-hit == false
-        uses: docker/setup-qemu-action@v1
-
-      - name: Build Cloudwatch Agent Operator Image and push to ECR
-        uses: docker/build-push-action@v4
-        if: steps.cached_binaries.outputs.cache-hit == false
-        with:
-          file: ./Dockerfile
-          context: .
-          push: true
-          tags: ${{ env.ECR_OPERATOR_STAGING_IMAGE }}
-          platforms: linux/amd64, linux/arm64
+      - name: Get Pod Name
+        id: get_pod_name
+        run: |
+          pod_name=$(kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/component=amazon-cloudwatch-agent,app.kubernetes.io/instance=amazon-cloudwatch.amazon-cloudwatch-agent -o=jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}')
+          echo "::set-output name=pod_name::$pod_name"
+      - name: Check if Pod is running
+        run: |
+          pod_name="${{ steps.get_pod_name.outputs.pod_name }}"
+          status=$(kubectl get pod "$pod_name" -n amazon-cloudwatch -o=jsonpath='{.status.phase}')
+          if [ "$status" != "Running" ]; then
+              echo "Pod $pod_name is not running. Exiting with error."
+              exit 1
+          else
+              echo "Pod $pod_name is running. Continue with the workflow."
+          fi
diff --git a/.github/workflows/eks-beta-add-on-integ-test.yml b/.github/workflows/eks-beta-add-on-integ-test.yml
--- a/.github/workflows/eks-beta-add-on-integ-test.yml
+++ b/.github/workflows/eks-beta-add-on-integ-test.yml
@@ -90,10 +90,16 @@ jobs:
 
             terraform init
             if terraform apply -var="beta=true" -var="addon_name=${{ github.event.inputs.addon_name }}" -var="addon_version=${{ github.event.inputs.addon_version }}" -var="k8s_version=${{ matrix.arrays.k8sVersion }}" --auto-approve; then
-              echo "Terraform apply succeeded"
-              kubectl describe nodes
-              kubectl get nodes -A
-              kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/component=amazon-cloudwatch-agent,app.kubernetes.io/instance=amazon-cloudwatch.amazon-cloudwatch-agent -o=jsonpath='{.items[*].metadata.name}'
+              pod_name=$(kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/component=amazon-cloudwatch-agent,app.kubernetes.io/instance=amazon-cloudwatch.amazon-cloudwatch-agent -o=jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}')
+              echo "::set-output name=pod_name::$pod_name"
+              pod_name="${{ steps.get_pod_name.outputs.pod_name }}"
+              status=$(kubectl get pod "$pod_name" -n amazon-cloudwatch -o=jsonpath='{.status.phase}')
+              if [ "$status" != "Running" ]; then
+                echo "Pod $pod_name is not running. Exiting with error."
+                terraform destroy -var="beta=true" -auto-approve && exit 1
+              else
+                echo "Pod $pod_name is running. Continue with the workflow."
+              fi
             else
               terraform destroy -var="beta=true" -auto-approve && exit 1
             fi
